FROM python:3.10-alpine3.22

RUN apk update && apk add --no-cache tini git fuse-overlayfs tini nodejs-current npm docker-cli

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . /app/

RUN uv sync --locked --no-dev

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

COPY entrypoint.native.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["tini", "-s", "--", "python", "-m", "mcp_anywhere", "serve", "http"]